name: Update badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: "0 2 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@master
          CREDLY_USER: <username_credly> # optional, but default will use the same from github
          
<!--START_SECTION:badges-->

    <div data-iframe-width="150" data-iframe-height="270" data-share-badge-id="9a630c64-e313-43d6-a1b0-6ac36940a120" data-share-badge-host="https://www.credly.com"></div><script type="text/javascript" async src="//cdn.credly.com/assets/utilities/embed.js"></script>
<!--END_SECTION:badges-->
